// <auto-generated />
namespace Spice.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addsubcategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addsubcategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202102201513106_Add subcategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
